spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${{CLIENT_ID}
            client-secret: ${{CLIENT_SECRET}
      resourceserver:
         jwt:
          issuer-uri: https://accounts.google.com
